---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  fs.inotify.max_user_instances: "8192"
  fs.inotify.max_user_watches: "1048576"
  net.core.rmem_max: "67108864"
  net.core.wmem_max: "67108864"
  net.ipv4.neigh.default.gc_thresh1: "4096"
  net.ipv4.neigh.default.gc_thresh2: "8192"
  net.ipv4.neigh.default.gc_thresh3: "16384"
  net.ipv4.tcp_fastopen: "3"
  user.max_user_namespaces: "11255"