---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DATABASE_URL: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres-rw.databases.svc.cluster.local.:5432/vaultwarden
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ADMIN_TOKEN }}"
        PUSH_INSTALLATION_ID: "{{ .PUSH_INSTALLATION_ID }}"
        PUSH_INSTALLATION_KEY:  "{{ .PUSH_INSTALLATION_KEY }}"

  data:
    - secretKey: VAULTWARDEN_ADMIN_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0736d3f-5a37-4294-91a5-119c9237b604
        property: admin_token
    - secretKey: PUSH_INSTALLATION_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0736d3f-5a37-4294-91a5-119c9237b604
        property: push_installation_id
    - secretKey: PUSH_INSTALLATION_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0736d3f-5a37-4294-91a5-119c9237b604
        property: push_installation_key
    - secretKey: POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0736d3f-5a37-4294-91a5-119c9237b604
        property: pg_user
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0736d3f-5a37-4294-91a5-119c9237b604
        property: pg_password

