---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        secrets.yaml: |
          wifi_ssid: "{{ .wifi_ssid }}"
          wifi_password: "{{ .wifi_password }}"
          api_encryption_key: "{{ .api_encryption_key }}"
  data:
    - secretKey: wifi_ssid
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 2ce16904-210c-4802-b097-55c892628aef
        property: wifi_ssid
    - secretKey: wifi_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 2ce16904-210c-4802-b097-55c892628aef
        property: wifi_password
    - secretKey: api_encryption_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 2ce16904-210c-4802-b097-55c892628aef
        property: api_encryption_key