---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
        PROWLARR__POSTGRES__HOST: postgres-rw.databases.svc.cluster.local
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: "{{ .PROWLARR_POSTGRES_USER }}"
        PROWLARR__POSTGRES__PASSWORD: "{{ .PROWLARR_POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES__MAINDB: prowlarr_main
  data:
    - secretKey: PROWLARR_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d757379c-7df3-4aff-9619-d6542fe0f990
        property: token
    - secretKey: PROWLARR_POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d757379c-7df3-4aff-9619-d6542fe0f990
        property: pg_user
    - secretKey: PROWLARR_POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d757379c-7df3-4aff-9619-d6542fe0f990
        property: pg_password
