---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname home-assistant
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync/local
    - ../../../../components/volsync/remote
    - ../../../../components/postgres-db
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: multus-networks
      namespace: networking
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: certificates
      namespace: networking
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/apps/default/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
      DB_NAME: home_assistant
      DB_USER: home-assistant
      DB_BITWARDEN_ID: ade9622d-3723-4cc7-b2d7-c53ca02aa476
