---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: KOPIA_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4dee8abf-9758-430d-ad79-1da57708cd40
        property: kopia_password
    - secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4dee8abf-9758-430d-ad79-1da57708cd40
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4dee8abf-9758-430d-ad79-1da57708cd40
        property: secret_key
