---
# yaml-language-server: $$schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-postgres
spec:
  target:
    name: ${APP}-postgres
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .pg_user }}"
        password: "{{ .pg_password }}"
  data:
    - secretKey: pg_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${DB_BITWARDEN_ID}
        property: pg_user
    - secretKey: pg_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${DB_BITWARDEN_ID}
        property: pg_password
