---
# yaml-language-server: $$schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ${APP}-postgres
spec:
  cluster:
    name: postgres
  comment: "${APP} database role"
  createdb: false
  createrole: false
  databaseRoleReclaimPolicy: ${ROLE_RECLAIM_POLICY:-retain}
  inherit: true
  inRoles:
    - pg_monitor
  login: true
  name: ${DB_USER}
  passwordSecret:
    name: ${APP}-postgres
  superuser: false
