---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname vaultwarden
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync/local
    - ../../../../components/volsync/remote
    - ../../../../components/postgres-db
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: smtp-relay
      namespace: default
    - name: certificates
      namespace: networking
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/apps/default/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *appname
      KOPIUR_CAPACITY: 1Gi
      VOLSYNC_CAPACITY: 1Gi
      DB_NAME: vaultwarden
      DB_USER: vaultwarden
      DB_BITWARDEN_ID: c0736d3f-5a37-4294-91a5-119c9237b604
