---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .BOOKBOSS_ENCRYPTION_SECRET }}"
  data:
    - secretKey: BOOKBOSS_ENCRYPTION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: fae049ae-922d-4678-beed-a9c34f963b68
        property: token
