---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname lldap
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/postgres-db
  postBuild:
    substitute:
      APP: *appname
      DB_NAME: lldap
      DB_USER: lldap
      DB_BITWARDEN_ID: 067f068f-0447-4167-a0a8-a7773a3aa5f1
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: external-secrets-stores
      namespace: external-secrets
    - name: certificates
      namespace: networking
  path: ./kubernetes/apps/default/lldap/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
