---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: konflate-webhook-token-secret
    template:
      data:
        KONFLATE_APP_CLIENT_ID: "{{ .CLIENT_ID }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ .PRIVATE_KEY }}"
        KONFLATE_WEBHOOK_SECRET: "{{ .WEBHOOK_SECRET }}"
  data:
    - secretKey: CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: be4806ca-404b-44f7-bb1d-fd80ca67909c
        property: client_id
    - secretKey: PRIVATE_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: be4806ca-404b-44f7-bb1d-fd80ca67909c
        property: private_key
        decodingStrategy: Base64
    - secretKey: WEBHOOK_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: be4806ca-404b-44f7-bb1d-fd80ca67909c
        property: webhook_secret
