---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        # API
        OPENCODE_GO_API_KEY: "{{ .OPENCODE_API_KEY }}"
        GOOGLE_API_KEY: "{{ .GOOGLE_API_KEY }}"
        GROQ_API_KEY: "{{ .GROQ_API_KEY }}"
  data:
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 60d73745-cb68-460c-b6e7-896e262c1627
        property: master_key
    - secretKey: OPENCODE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 60d73745-cb68-460c-b6e7-896e262c1627
        property: opencode_api_key
    - secretKey: GOOGLE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 60d73745-cb68-460c-b6e7-896e262c1627
        property: google_api_key
    - secretKey: GROQ_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 60d73745-cb68-460c-b6e7-896e262c1627
        property: groq_api_key

