---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
        CF_ZONE_ID: "{{ .CLOUDFLARE_ZONE_ID }}"
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 90e5e570-8a6a-42a3-87fd-4d93c591dc6d
        property: token_external
    - secretKey: CLOUDFLARE_ZONE_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 90e5e570-8a6a-42a3-87fd-4d93c591dc6d
        property: zone_id
