---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: llmkube
spec:
  chartRef:
    kind: OCIRepository
    name: llmkube
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    modelCache:
      enabled: true
      mode: perService
      size: 20Gi
      storageClass: openebs-hostpath
    prometheus:
      inferencePodMonitor:
        enabled: false
