---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname adventurelog
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/postgres-db
    - ../../../../components/volsync/local
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: smtp-relay
      namespace: default
    - name: certificates
      namespace: networking
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/apps/default/adventurelog/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_PUID: 0
      VOLSYNC_CAPACITY: 1Gi
      DB_NAME: adventurelog
      DB_USER: adventurelog
      DB_BITWARDEN_ID: de49178f-239e-4590-b281-e11fcb718dd9
