---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname open-webui
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync/local
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
    - name: dragonfly-cluster
      namespace: databases
    - name: searxng
      namespace: ai
    - name: certificates
      namespace: networking
  path: ./kubernetes/apps/ai/open-webui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *appname
