---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MEMINI_API_KEY: "{{ .MEMINI_API_KEY }}"
  data:
    - secretKey: MEMINI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 89932561-7139-4d7f-9be6-428cad49d1cf
        property: api_key
