---
# yaml-language-server: $$schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-postgres
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: ${APP}-postgres
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/components/postgres-db/manifests
  postBuild:
    substitute:
      APP: ${APP}
      DB_BITWARDEN_ID: ${DB_BITWARDEN_ID}
      DB_EXTENSIONS: ${q:='}${DB_EXTENSIONS:=}${q:='}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  timeout: 3m
