---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname radarr
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/keda/nfs-scaler
    - ../../../../components/postgres-db
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: external-secrets-stores
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: keda
      namespace: monitoring
    - name: certificates
      namespace: networking
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/apps/default/radarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *appname
      DB_NAME: radarr_main
      DB_USER: radarr
      DB_BITWARDEN_ID: 133e1c1d-894d-4fc7-a69c-d44bd3fe090f
