---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname memini
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/postgres-db
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cloudnative-pg-cluster
      namespace: databases
  interval: 30m
  path: ./kubernetes/apps/ai/memini/app
  postBuild:
    substitute:
      APP: *appname
      DB_BITWARDEN_ID: 89932561-7139-4d7f-9be6-428cad49d1cf
      DB_EXTENSIONS: |
        [
          { name: vector },
          { name: vchord }
        ]
      DB_NAME: memini
      DB_USER: memini
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
