---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adventurelog
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: adventurelog
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/seanmorley15/adventurelog
              tag: v0.13.0@sha256:08bf228403dc99559a661e0d03a5ff08823da21a47fb7ab281dcef98794571ec
            envFrom:
              - secretRef:
                  name: adventurelog-secret
            env:
              SITE_URL: https://adventurelog.${SECRET_DOMAIN}
              DEBUG: "False"
              EMAIL_BACKEND: email
              EMAIL_HOST: smtp-relay.default.svc.cluster.local
              EMAIL_PORT: 2525
              EMAIL_USE_TLS: "False"
              DEFAULT_FROM_EMAIL: ${SECRET_SMTP_SENDER}
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 90
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1Gi

    service:
      app:
        controller: app
        ports:
          http:
            port: 80

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          app:
            app:
              - path: /code/media
