---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./ha-mcp/ks.yaml
  # - ./hermes/ks.yaml
  - ./litellm/ks.yaml
  - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
  - ./toolhive/ks.yaml
