---
version: "3"

tasks:
  render:
    desc: Render Talos configs with topf
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/secrets.sops.yaml
      - test -f {{.K8S_DIR}}/talos/topf.yaml
    vars:
      ONLINE: '{{.ONLINE | default "false"}}'
    cmds:
      - topf render --output {{.K8S_DIR}}/talos/output
        {{ if eq "true" .ONLINE }}--online{{ end }}

  apply:
    desc: Apply Talos config to all nodes with topf
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/secrets.sops.yaml
      - test -f {{.K8S_DIR}}/talos/topf.yaml
    vars:
      DRY_RUN: '{{.DRY_RUN | default "false"}}'
      CONFIRM: '{{.CONFIRM | default "true"}}'
    cmds:
      - topf apply
        {{ if eq "true" .DRY_RUN }}--dry-run{{ end }}
        {{ if eq "false" .CONFIRM }}--confirm=false{{ end }}

  apply-node:
    desc: Apply Talos config to a single node [NODE=required]
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/topf.yaml
    requires:
      vars:
        - NODE
    cmds:
      - topf apply --nodes-filter "{{.NODE}}"

  upgrade:
    desc: Upgrade Talos on all nodes with topf
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/topf.yaml
    cmds:
      - topf upgrade

  upgrade-node:
    desc: Upgrade Talos on a single node [NODE=required]
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/topf.yaml
    requires:
      vars:
        - NODE
    cmds:
      - topf upgrade --nodes-filter "{{.NODE}}" --reboot-mode powercycle

  upgrade-k8s:
    desc: Upgrade Kubernetes across the whole cluster
    vars:
      TALOS_CONTROLLER:
        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
      KUBERNETES_VERSION:
        sh: yq -r '.kubernetesVersion' {{.K8S_DIR}}/talos/topf.yaml
    cmds:
      - talosctl --nodes {{.TALOS_CONTROLLER}} upgrade-k8s --to $KUBERNETES_VERSION
    preconditions:
      - talosctl --nodes {{.TALOS_CONTROLLER}} get machineconfig
      - talosctl config info
      - test -f {{.K8S_DIR}}/talos/talosconfig
      - which jq talosctl yq

  reset-node:
    desc: Reset a Talos node
    prompt: Reset Talos node {{.node}} ... continue?
    cmds:
      - topf reset --nodes-filter "{{.node}}" --full=false --graceful=false
    requires:
      vars: ["node"]
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/topf.yaml

  reset-cluster:
    desc: Reset Talos across the whole cluster
    prompt: Reset the Talos cluster ... continue?
    cmds:
      - topf reset --full=false --graceful=false
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/topf.yaml

  talosconfig:
    desc: Generate a talosconfig from the secrets bundle
    preconditions:
      - which topf
      - test -f {{.K8S_DIR}}/talos/secrets.sops.yaml
    cmds:
      - topf talosconfig > {{.K8S_DIR}}/talos/talosconfig