---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        Settings.json: |
          {
            "General": {
              "AuthenticationSecret": "{{ .AUTH_SECRET }}",
              "DownloadImages": false,
              "RenewImagesDuration": 30,
              "RefreshAlbumPeopleInterval": 12,
              "PhotoDateFormat": "MM/dd/yyyy",
              "ImageLocationFormat": "City,State,Country",
              "WeatherApiKey": "{{ .OWM_APIKEY }}",
              "UnitSystem": "metric",
              "WeatherLatLong": "{{ .HASS_LATITUDE }},{{ .HASS_LONGITUDE }}",
              "Language": "de",
              "Interval": 20,
              "TransitionDuration": 2,
              "ShowClock": true,
              "ClockFormat": "HH:mm",
              "ClockDateFormat": "EEE, d. MMM",
              "ShowProgressBar": true,
              "ShowPhotoDate": true,
              "ShowImageDesc": true,
              "ShowPeopleDesc": true,
              "ShowAlbumName": true,
              "ShowImageLocation": true,
              "PrimaryColor": "#f5deb3",
              "SecondaryColor": "#000000",
              "Style": "none",
              "BaseFontSize": "17px",
              "ShowWeatherDescription": true,
              "ImageZoom": true,
              "ImagePan": false,
              "ImageFill": false,
              "PlayAudio": false,
              "Layout": "splitview"
            },
            "Accounts": [
              {
                "ImmichServerUrl": "http://immich-server.default.svc.cluster.local:2283",
                "ApiKey": "{{ .IMMICH_APIKEY }}",
                "ImagesFromDate": "2018-01-01T00:00:00.000Z",
                "ShowMemories": false,
                "ShowFavorites": false,
                "ShowArchived": false,
                "ShowVideos": false
              }
            ]
          }

  data:
    - secretKey: IMMICH_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1349341e-663a-4e35-b567-16bbad606144
        property: immich_apikey
    - secretKey: AUTH_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1349341e-663a-4e35-b567-16bbad606144
        property: auth_secret
    - secretKey: OWM_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1349341e-663a-4e35-b567-16bbad606144
        property: openweathermap_apikey
    - secretKey: HASS_LATITUDE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: latitude
    - secretKey: HASS_LONGITUDE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: longitude
