---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        ApiKey: "{{ .IMMICH_APIKEY }}"
        AuthenticationSecret: "{{ .AUTH_SECRET }}"

  data:
    - secretKey: IMMICH_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1349341e-663a-4e35-b567-16bbad606144
        property: immich_apikey
    - secretKey: AUTH_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1349341e-663a-4e35-b567-16bbad606144
        property: auth_secret