---
apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
    - 192.168.20.0/24
labels:
  node.kubernetes.io/exclude-from-external-load-balancers:
    $patch: delete
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete