---
machine:
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.36.4
    extraMounts:
      - destination: /var/openebs/local
        type: bind
        source: /var/openebs/local
        options: ["bind", "rshared", "rw"]
    extraConfig:
      featureGates:
        ImageVolume: true
      maxPods: 150
      allowedUnsafeSysctls:
        - net.ipv6.conf.*