---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        HOMEASSISTANT_TOKEN: "{{ .HOMEASSISTANT_TOKEN }}"
  data:
    - secretKey: HOMEASSISTANT_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: ha_mcp_token
