---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Apikeys
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        # Apps
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        PLEX_URL: "{{ .PLEX_URL }}"
        # Hermes
        API_SERVER_KEY: "{{ .HERMES_API_SERVER_KEY }}"
  data:
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 60d73745-cb68-460c-b6e7-896e262c1627
        property: master_key
    - secretKey: HERMES_API_SERVER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c83883ba-cda5-4f27-93ed-51b02d205c08
        property: api_server_key
    - secretKey: DISCORD_BOT_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c83883ba-cda5-4f27-93ed-51b02d205c08
        property: discord_bot_token
    - secretKey: DISCORD_ALLOWED_USERS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c83883ba-cda5-4f27-93ed-51b02d205c08
        property: discord_user_id
    - secretKey: PLEX_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3a2aa0ba-39ad-4b7e-b0c3-8861d16a56d0
        property: token
    - secretKey: PLEX_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3a2aa0ba-39ad-4b7e-b0c3-8861d16a56d0
        property: url
