---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_POSTGRES_URL: |-
          postgresql://{{ .HASS_POSTGRES_USER }}:{{ .HASS_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local/home_assistant

  data:
    - secretKey: HASS_ELEVATION
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: elevation
    - secretKey: HASS_LATITUDE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: latitude
    - secretKey: HASS_LONGITUDE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: longitude
    - secretKey: HASS_POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: pg_user
    - secretKey: HASS_POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ade9622d-3723-4cc7-b2d7-c53ca02aa476
        property: pg_password

