---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: prometheus
    name: Prometheus
    access: proxy
    isDefault: true
    uid: prometheus
    url: http://prometheus-operated.monitoring.svc.cluster.local:9090
    jsonData:
      timeInterval: 1m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: alertmanager
    name: Alertmanager
    access: proxy
    uid: alertmanager
    url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
    jsonData:
      implementation: prometheus
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: postgres-ha
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: postgres
    name: Postgres HA
    access: proxy
    uid: homeassistant-postgres
    url: postgres-rw.databases.svc.cluster.local:5432
    user: placeholder
    secureJsonData:
      password: placeholder
    jsonData:
      database: home_assistant
      sslmode: disable
  valuesFrom:
    - targetPath: "datasource.user"
      valueFrom:
        secretKeyRef:
          name: grafana-secret
          key: HASS_POSTGRES_USER
    - targetPath: "datasource.secureJsonData.password"
      valueFrom:
        secretKeyRef:
          name: grafana-secret
          key: HASS_POSTGRES_PASS
