---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/gpu
    - ../../../../components/keda/nfs-scaler
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: keda
      namespace: monitoring
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/apps/default/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *appname
      KOPIUR_CAPACITY: 100Gi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex-auto-languages
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: plex
      namespace: default
  path: ./kubernetes/apps/default/plex/auto-languages
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kometa
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: plex
      namespace: default
    - name: tautulli
      namespace: default
    - name: radarr
      namespace: default
    - name: sonarr
      namespace: default
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/apps/default/plex/kometa
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
      KOPIUR_CAPACITY: 10Gi
